version: '3'

services:
  backend:
    build: .
    container_name: newpace
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: database
      PORT: 3001

  database:
    image: mysql:8.0.29
    container_name: newpace_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: newpacedb
    ports:
      - 33060:3306
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      

networks:
  default:
    name: newpace_net